[theme]
primaryColor="#4F00FF"
#backgroundColor="#0E1117"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#FAFAFA"
font="Sans serif"

[server]
headless = true
runOnSave = true
fileWatcherType = "poll"